/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'CustomIcon';

  static const IconData shift = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData time_off = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData change_password = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData department = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData designation = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData employee = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData geo_fence = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData holiday = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData late_comers = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData punch_visits = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData custom_date = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData logs = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData yesterday = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData thirty = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData reports = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData seven = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData flexi_time = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData early_leaver = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData time_off_home = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData visits = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData group_2 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData logs_2 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData phone_call = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData email_icon = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData message_icon = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData visits_man = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData contact_directory = const IconData(0xe826, fontFamily: _kFontFam);

}